/*
  Copies the inject library out of index.html, so the store starts from exactly what the game has:

    injects/seed.json      the 16 injects, with an id each, and which one starts (DECK_START)
    injects/src/meta.json  the categories, types and footprint shapes (checked against on every save)
    injects/site/meta.js   the same, for the editor page

  Run:  node injects/tools/extract.js          (writes the files)
        node injects/tools/extract.js --check  (fails if they no longer match index.html; the tests use this)

  The store is seeded from seed.json ONCE, the first time it is read. After that the edited deck lives in
  the store and index.html's copy is only the offline fallback.
*/
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..", "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const slice = (a, b) => { const i = html.indexOf(a); if (i < 0) throw new Error("index.html no longer has: " + a); const j = html.indexOf(b, i); if (j < 0) throw new Error("index.html no longer has: " + b); return html.slice(i, j); };
const code = [slice("var SHAPES = {", "/* Type is context"), slice("var TYPES = {", "var CATS"), slice("var CATS = {", "var CRISIS_CELLS"), slice("var DECK = [", "DECK.forEach"), slice("var DECK_START =", "\n")].join("\n");
const { SHAPES, TYPES, CATS, DECK, DECK_START } = new Function(code + "; return { SHAPES, TYPES, CATS, DECK, DECK_START };")();

const meta = {
  types: TYPES,
  cats: Object.fromEntries(Object.entries(CATS).map(([k, v]) => [k, v.label])),
  shapes: SHAPES,
};
const seed = { start: DECK_START, injects: DECK.map((c, i) => ({ id: "i" + String(i + 1).padStart(2, "0"), ...JSON.parse(JSON.stringify(c)) })) };

const out = {
  "injects/seed.json": JSON.stringify(seed, null, 1) + "\n",
  "injects/src/meta.json": JSON.stringify(meta, null, 1) + "\n",
  "injects/site/meta.js": "/* Generated by tools/extract.js from index.html. Do not edit. */\nwindow.META = " + JSON.stringify(meta) + ";\n",
};
if (process.argv.includes("--check")) {
  const stale = Object.keys(out).filter(f => !fs.existsSync(path.join(root, f)) || fs.readFileSync(path.join(root, f), "utf8") !== out[f]);
  if (stale.length) { console.error("Out of date with index.html: " + stale.join(", ") + ". Run: node injects/tools/extract.js"); process.exit(1); }
  console.log("seed.json, meta.json and meta.js match index.html");
} else {
  for (const [f, text] of Object.entries(out)) fs.writeFileSync(path.join(root, f), text);
  console.log("wrote " + Object.keys(out).join(", ") + " (" + seed.injects.length + " injects, starting at " + seed.start + ")");
}
